development:
  adapter: postgresql
  encoding: unicode
  database: posto_development
  pool: 5
  username: postgres
  password: h
  schema_search_path: posto0

test:
  adapter: postgresql
  encoding: unicode
  database: posto_test
  pool: 5
  username: postgres
  password: h
  schema_search_path: posto0
