development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: posto_development
  pool: 5
  username: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: posto_test
  pool: 5
  username: root
  socket: /tmp/mysql.sock
